# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- script: |
    cd chakai-p2e-app
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Sub Service Connection'  # The service connection you created in Azure DevOps
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Log in to Azure using Service Principal (via Azure CLI)
      echo "Logging in to Azure..."
      
      # Set variables
      STORAGE_ACCOUNT_NAME="chakaip2efrontend"
      #STORAGE_CONTAINER_NAME="ChakaiP2EContainer"
      LOCAL_DIRECTORY="./chakai-p2e-app/.next/standalone/"  # Directory inside the Docker container to upload
      RESOURCE_GROUP="ChakaiP2E"

      # Retrieve Storage Account Key dynamically using Azure CLI
      ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)

      # Create the container if it doesn't exist
      #echo "Creating container if it doesn't exist..."
      #az storage container create \
      #  --name $STORAGE_CONTAINER_NAME \
      #  --account-name $STORAGE_ACCOUNT_NAME \
      #  --account-key $ACCOUNT_KEY || echo "Container already exists, skipping creation"
      
      # Clean up the $web container
      echo "Deleting all blobs in the \$web container..."
      az storage blob delete-batch --account-name $STORAGE_ACCOUNT_NAME --source '$web' --auth-mode key
      echo "All blobs in \$web container have been deleted."

      # Upload the directory to Azure Blob Storage
      echo "Uploading directory to Azure Blob Storage..."
      az storage blob upload-batch \
        --account-name $STORAGE_ACCOUNT_NAME \
        --account-key $ACCOUNT_KEY \
        --destination '$web' \
        --source $LOCAL_DIRECTORY
        --overwrite

  displayName: 'Create Container and Upload Directory to Azure Blob Storage'